dist: xenial

language: node_js
node_js:
  - '12.16'

addons:
  chrome: stable

#branches:
#  only:
#    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

stages:
  - test
  - deploy

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
  # -- TEST -- #
  - stage: test
    name: "Lint"
    script:
      - ng lint ash-material-file-input
  - stage: test
    name: "Unit tests"
    script:
      - ng test ash-material-file-input --watch false --browsers ChromeHeadless
  
  # -- BUILD & DEPLOY -- #
  - stage: deploy
    name: "Build & deploy"
    script:
      - ng build --prod ash-material-file-input
      - ng build example --prod --base-href /ash-material-file-input/
    after_success:
      - echo "Build successfull - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
    before_deploy:
      - zip -r9 ash-material-file-input-$TRAVIS_TAG.zip dist/ash-material-file-input
    deploy: 
      - provider: pages
        local_dir: "dist/example"
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
          tags: true
      - provider: release
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: ash-material-file-input-$TRAVIS_TAG.zip
        draft: true
        on:
          branch: master
          tags: true