dist: xenial

language: node_js
node_js:
  - '12.16'

addons:
  chrome: stable

stages:
  - test
  - deploy

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
  # -- TEST -- #
  - stage: test
    name: "Lint"
    script:
      - ng lint ash-material-file-input
  - stage: test
    name: "Unit tests"
    script:
      - ng test ash-material-file-input --watch false --browsers ChromeHeadless
  
  # -- BUILD & DEPLOY -- #
  - stage: deploy
    name: "Build & deploy"
    script:
      - ng build --prod ash-material-file-input
      - ng build example --prod --base-href /ash-material-file-input/
    after_success:
      - echo "Build successfull - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
    deploy: 
      provider: pages
      local_dir: "dist/example"
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      on:
        branch: master