dist: xenial

language: node_js
node_js:
  - '12.16'

addons:
  chrome: stable
before_install:


cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng test --watch false --browsers ChromeHeadless