dist: xenial

language: node_js
node_js:
  - '12.16'

addons:
  chrome: stable

branches:
  except:
    - develop

stages:
  - test
  - deploy

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
  # -- TEST -- #
  - stage: test
    name: "Lint"
    script:
      - npm run lint:lib
  - stage: test
    name: "Unit tests"
    before_script:
      - npm i coveralls
    script:
      - npm run test:lib
    after_success:
      - cat ./coverage/ash-material-file-input/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  
  # -- BUILD & DEPLOY -- #
  - stage: deploy
    name: "Build & deploy"
    script:
      - npm run build:lib
      - npm run build:example
    after_success:
      - echo "Build successfull - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
    before_deploy:
      - zip -r9 ash-material-file-input-$TRAVIS_TAG.zip dist/ash-material-file-input
    deploy: 
      - provider: pages
        local_dir: "dist/example"
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
      - provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: ash-material-file-input-$TRAVIS_TAG.zip
        on:
          branch: master
          tags: true